language: clojure
sudo: false
jdk:
- oraclejdk7
install:
- wget -O boot https://github.com/boot-clj/boot/releases/download/2.2.0/boot.sh
- chmod 755 boot
- mkdir -p "$HOME/.local/bin"
- mv boot "$HOME/.local/bin"
- export PATH="$HOME/.local/bin:$PATH"
script: boot build-jar && cd example/ && boot jasmin run -m example.HelloWorld && boot jasmin uber jar -m example.HelloWorld && java -jar target/project.jar